//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string UOM { get; set; }
        public string SKU { get; set; }
        public string SN { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> OrderLevel { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string MobileNumber { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string ORNumber { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string TransactionNumber { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Items Items { get; set; }
    }
}
